# Site settings
layout: post
comments: true
title: Childsish Musings
description: Some programming, perhaps a little statistics and bioinformatics
baseurl: ""
url: "https://childsish.github.com"
twitter_username: childsish
github_username:  childsish

# Build settings
markdown: kramdown
