# Site settings
layout: post
comments: true
title: Childs Play
description: Some programming, perhaps a little statistics and bioinformatics
baseurl: ""
url: "https://childsish.github.com"
twitter_username: childsish
github_username:  childsish

# Build settings
markdown: kramdown

gems:
 - jekyll-gist
 - certified
